// Timeline Bíblico — dados das cartas
// Fonte das datas: BibleHub Bible Timeline (https://biblehub.com/timeline/) — todas as datas são aproximadas.
// year: negativo = a.C., positivo = d.C. Empates de ano são aceitos em qualquer ordem no jogo.
// img: arquivo esperado em images/<id>.png (se não existir, o jogo usa o placeholder com emoji).

const CARDS = [
  // ===== VELHO TESTAMENTO =====
  { id: "criacao",           year: -4000, display: "Antes de 4000 a.C.", pt: "A Criação",                          en: "The Creation",                        ref: "Gênesis 1",       emoji: "🌍" },
  { id: "queda",             year: -4000, display: "Antes de 4000 a.C.", pt: "A Queda do Homem",                   en: "The Fall of Man",                     ref: "Gênesis 3",       emoji: "🍎" },
  { id: "caim-abel",         year: -3000, display: "Antes de 3000 a.C.", pt: "Caim Mata Abel",                     en: "Cain Kills Abel",                     ref: "Gênesis 4",       emoji: "🌾" },
  { id: "diluvio",           year: -2500, display: "Antes de 2500 a.C.", pt: "O Grande Dilúvio",                   en: "The Great Flood",                     ref: "Gênesis 7",       emoji: "🚢" },
  { id: "babel",             year: -2100, display: "Antes de 2100 a.C.", pt: "A Torre de Babel",                   en: "The Tower of Babel",                  ref: "Gênesis 11",      emoji: "🗼" },
  { id: "chamado-abrao",     year: -2091, display: "2091 a.C.",          pt: "Deus Chama Abrão",                   en: "God Calls Abram",                     ref: "Gênesis 12",      emoji: "✨" },
  { id: "sodoma",            year: -2067, display: "2067 a.C.",          pt: "A Destruição de Sodoma",             en: "The Destruction of Sodom",            ref: "Gênesis 19",      emoji: "🔥" },
  { id: "nasc-isaque",       year: -2066, display: "2066 a.C.",          pt: "Nascimento de Isaque",               en: "Isaac Is Born",                       ref: "Gênesis 21",      emoji: "👶" },
  { id: "sacrificio-isaque", year: -2054, display: "2054 a.C.",          pt: "O Sacrifício de Isaque",             en: "The Offering of Isaac",               ref: "Gênesis 22",      emoji: "🐏" },
  { id: "jaco-esau",         year: -2006, display: "2006 a.C.",          pt: "Nascimento de Jacó e Esaú",          en: "Birth of Jacob and Esau",             ref: "Gênesis 25",      emoji: "👬" },
  { id: "escada-jaco",       year: -1928, display: "1928 a.C.",          pt: "A Escada de Jacó",                   en: "Jacob's Ladder",                      ref: "Gênesis 28",      emoji: "🪜" },
  { id: "jose-vendido",      year: -1898, display: "1898 a.C.",          pt: "José Vendido como Escravo",          en: "Joseph Sold into Slavery",            ref: "Gênesis 37",      emoji: "🧥" },
  { id: "jose-sonhos",       year: -1886, display: "1886 a.C.",          pt: "José Interpreta os Sonhos do Faraó", en: "Joseph Interprets Pharaoh's Dreams",  ref: "Gênesis 41",      emoji: "👑" },
  { id: "nasc-moises",       year: -1525, display: "1525 a.C.",          pt: "Moisés no Cesto do Nilo",            en: "The Birth and Adoption of Moses",     ref: "Êxodo 2",         emoji: "🧺" },
  { id: "dez-pragas",        year: -1446, display: "1446 a.C.",          pt: "As Dez Pragas do Egito",             en: "The Ten Plagues on Egypt",            ref: "Êxodo 7–12",      emoji: "🐸" },
  { id: "mar-vermelho",      year: -1446, display: "1446 a.C.",          pt: "A Travessia do Mar Vermelho",        en: "Crossing the Red Sea",                ref: "Êxodo 14",        emoji: "🌊" },
  { id: "dez-mandamentos",   year: -1446, display: "1446 a.C.",          pt: "Os Dez Mandamentos",                 en: "Moses Receives the Commandments",     ref: "Êxodo 20",        emoji: "📜" },
  { id: "serpente-bronze",   year: -1407, display: "1407 a.C.",          pt: "A Serpente de Bronze",               en: "The Bronze Snake",                    ref: "Números 21",      emoji: "🐍" },
  { id: "morte-moises",      year: -1406, display: "1406 a.C.",          pt: "A Morte de Moisés",                  en: "The Death of Moses",                  ref: "Deuteronômio 34", emoji: "⛰️" },
  { id: "jerico",            year: -1406, display: "1406 a.C.",          pt: "A Queda de Jericó",                  en: "The Fall of Jericho",                 ref: "Josué 6",         emoji: "🎺" },
  { id: "sol-detido",        year: -1405, display: "1405 a.C.",          pt: "O Sol se Detém sobre Gibeão",        en: "The Sun Stands Still",                ref: "Josué 10",        emoji: "☀️" },
  { id: "debora",            year: -1235, display: "1235 a.C.",          pt: "Débora e Baraque",                   en: "Deborah and Barak",                   ref: "Juízes 4",        emoji: "🌴" },
  { id: "gideao",            year: -1169, display: "1169 a.C.",          pt: "Gideão e os Midianitas",             en: "Gideon and the Midianites",           ref: "Juízes 6–8",      emoji: "🏺" },
  { id: "rute",              year: -1140, display: "1140 a.C.",          pt: "Rute e Boaz",                        en: "Ruth and Boaz",                       ref: "Rute 1–4",        emoji: "🌾" },
  { id: "sansao-dalila",     year: -1075, display: "1075 a.C.",          pt: "Sansão e Dalila",                    en: "Samson and Delilah",                  ref: "Juízes 16",       emoji: "💪" },
  { id: "saul-rei",          year: -1043, display: "1043 a.C.",          pt: "Saul se Torna Rei",                  en: "Saul Becomes King",                   ref: "1 Samuel 10",     emoji: "👑" },
  { id: "davi-golias",       year: -1024, display: "1024 a.C.",          pt: "Davi Vence Golias",                  en: "David Kills Goliath",                 ref: "1 Samuel 17",     emoji: "🪨" },
  { id: "davi-rei",          year: -1003, display: "1003 a.C.",          pt: "Davi Reina sobre Todo Israel",       en: "David Reigns over All Israel",        ref: "2 Samuel 5",      emoji: "🎼" },
  { id: "arca-jerusalem",    year: -1000, display: "1000 a.C.",          pt: "A Arca Chega a Jerusalém",           en: "The Ark Is Brought to Jerusalem",     ref: "2 Samuel 6",      emoji: "🕍" },
  { id: "templo-salomao",    year: -966,  display: "966 a.C.",           pt: "A Construção do Templo de Salomão",  en: "The Building of Solomon's Temple",    ref: "1 Reis 6",        emoji: "🏛️" },
  { id: "rainha-saba",       year: -946,  display: "946 a.C.",           pt: "A Rainha de Sabá Visita Salomão",    en: "The Queen of Sheba Visits Solomon",   ref: "1 Reis 10",       emoji: "💎" },
  { id: "reino-dividido",    year: -931,  display: "931 a.C.",           pt: "O Reino é Dividido",                 en: "The Kingdom Is Divided",              ref: "1 Reis 12",       emoji: "⚔️" },
  { id: "elias-carmelo",     year: -863,  display: "863 a.C.",           pt: "Elias no Monte Carmelo",             en: "Elijah on Mount Carmel",              ref: "1 Reis 18",       emoji: "⚡" },
  { id: "elias-ceu",         year: -851,  display: "851 a.C.",           pt: "Elias é Levado ao Céu",              en: "Elijah Taken up to Heaven",           ref: "2 Reis 2",        emoji: "🔥" },
  { id: "jonas",             year: -760,  display: "760 a.C.",           pt: "Jonas e o Grande Peixe",             en: "Jonah and the Great Fish",            ref: "Jonas 1–4",       emoji: "🐋" },
  { id: "cativeiro-israel",  year: -722,  display: "722 a.C.",           pt: "Israel Levado ao Cativeiro",         en: "Israel Led into Captivity",           ref: "2 Reis 17",       emoji: "⛓️" },
  { id: "queda-jerusalem",   year: -586,  display: "586 a.C.",           pt: "A Queda de Jerusalém",               en: "The Fall of Jerusalem",               ref: "2 Reis 25",       emoji: "🏚️" },
  { id: "fornalha",          year: -585,  display: "585 a.C.",           pt: "A Fornalha Ardente",                 en: "Shadrach, Meshach and Abednego",      ref: "Daniel 3",        emoji: "🔥" },
  { id: "daniel-leoes",      year: -539,  display: "539 a.C.",           pt: "Daniel na Cova dos Leões",           en: "Daniel in the Lions' Den",            ref: "Daniel 6",        emoji: "🦁" },
  { id: "retorno-exilio",    year: -537,  display: "537 a.C.",           pt: "O Retorno do Exílio",                en: "The Exiles Return",                   ref: "Esdras 1–2",      emoji: "🏠" },
  { id: "ester",             year: -478,  display: "478 a.C.",           pt: "Ester se Torna Rainha",              en: "Esther Becomes Queen",                ref: "Ester 2",         emoji: "👸" },

  // ===== NOVO TESTAMENTO =====
  { id: "nasc-jesus",        year: -5,    display: "5 a.C.",             pt: "O Nascimento de Jesus",              en: "The Birth of Jesus",                  ref: "Lucas 2",         emoji: "⭐" },
  { id: "menino-templo",     year: 8,     display: "8 d.C.",             pt: "O Menino Jesus no Templo",           en: "The Boy Jesus at the Temple",         ref: "Lucas 2:41",      emoji: "📖" },
  { id: "batismo",           year: 26,    display: "26 d.C.",            pt: "O Batismo de Jesus",                 en: "The Baptism of Jesus",                ref: "Mateus 3:13",     emoji: "🕊️" },
  { id: "cana",              year: 27,    display: "27 d.C.",            pt: "As Bodas de Caná",                   en: "The Wedding at Cana",                 ref: "João 2",          emoji: "🍷" },
  { id: "sermao-monte",      year: 27,    display: "27 d.C.",            pt: "O Sermão do Monte",                  en: "The Sermon on the Mount",             ref: "Mateus 5–7",      emoji: "🗻" },
  { id: "multiplicacao",     year: 29,    display: "29 d.C.",            pt: "A Multiplicação dos Pães",           en: "Jesus Feeds the 5,000",               ref: "João 6",          emoji: "🍞" },
  { id: "transfiguracao",    year: 29,    display: "29 d.C.",            pt: "A Transfiguração",                   en: "The Transfiguration",                 ref: "Mateus 17",       emoji: "🌟" },
  { id: "lazaro",            year: 30,    display: "30 d.C.",            pt: "A Ressurreição de Lázaro",           en: "Jesus Raises Lazarus",                ref: "João 11",         emoji: "🪦" },
  { id: "crucificacao",      year: 30,    display: "30 d.C.",            pt: "A Crucificação de Jesus",            en: "The Crucifixion",                     ref: "João 19",         emoji: "✝️" },
  { id: "ressurreicao",      year: 30,    display: "30 d.C.",            pt: "A Ressurreição de Jesus",            en: "The Resurrection",                    ref: "João 20",         emoji: "🌅" },
  { id: "pentecostes",       year: 30,    display: "30 d.C.",            pt: "O Pentecostes",                      en: "Pentecost",                           ref: "Atos 2",          emoji: "🔥" },
  { id: "estevao",           year: 31,    display: "31 d.C.",            pt: "O Apedrejamento de Estêvão",         en: "The Stoning of Stephen",              ref: "Atos 7",          emoji: "🙏" },
  { id: "conversao-saulo",   year: 34,    display: "34 d.C.",            pt: "A Conversão de Saulo",               en: "Saul's Conversion",                   ref: "Atos 9",          emoji: "💡" },
  { id: "pedro-gentios",     year: 37,    display: "37 d.C.",            pt: "Pedro Prega aos Gentios",            en: "Peter Preaches to the Gentiles",      ref: "Atos 10",         emoji: "🌍" },
  { id: "pedro-prisao",      year: 42,    display: "42 d.C.",            pt: "Pedro Libertado da Prisão",          en: "Peter Led from Prison by the Angel",  ref: "Atos 12",         emoji: "🔓" },
  { id: "viagem-paulo",      year: 48,    display: "48 d.C.",            pt: "A 1ª Viagem Missionária de Paulo",   en: "Paul's First Missionary Journey",     ref: "Atos 13",         emoji: "⛵" },
  { id: "romanos",           year: 57,    display: "57 d.C.",            pt: "Paulo Escreve aos Romanos",          en: "Paul Writes to the Romans",           ref: "Romanos 1–16",    emoji: "✍️" },
  { id: "naufragio",         year: 62,    display: "62 d.C.",            pt: "O Naufrágio de Paulo",               en: "Paul's Shipwreck at Malta",           ref: "Atos 27",         emoji: "🌪️" },
  { id: "apocalipse",        year: 95,    display: "95 d.C.",            pt: "O Apocalipse em Patmos",             en: "John's Revelation on Patmos",         ref: "Apocalipse 1–22", emoji: "📯" },

  // ===== EXPANSÃO (60 cartas) — Velho Testamento =====
  { id: "arco-iris",         year: -2500, display: "Antes de 2500 a.C.", pt: "A Aliança do Arco-Íris",             en: "Covenant of the Rainbow",             ref: "Gênesis 9",       emoji: "🌈" },
  { id: "jo",                year: -2100, display: "Antes de 2100 a.C.", pt: "O Sofrimento e a Fé de Jó",          en: "Job's Suffering and Faith",           ref: "Jó 1–42",         emoji: "🐫" },
  { id: "tres-visitantes",   year: -2067, display: "2067 a.C.",          pt: "Os Três Visitantes de Abraão",       en: "God Promises the Birth of Isaac",     ref: "Gênesis 18",      emoji: "⛺" },
  { id: "isaque-rebeca",     year: -2026, display: "2026 a.C.",          pt: "Isaque se Casa com Rebeca",          en: "Isaac Marries Rebekah",               ref: "Gênesis 24",      emoji: "💍" },
  { id: "esau-primogenitura",year: -1978, display: "1978 a.C.",          pt: "Esaú Vende a Primogenitura",         en: "Esau Sells His Birthright",           ref: "Gênesis 25:29",   emoji: "🍲" },
  { id: "bencao-jaco",       year: -1929, display: "1929 a.C.",          pt: "Jacó Recebe a Bênção de Isaque",     en: "Jacob Gets Isaac's Blessing",         ref: "Gênesis 27",      emoji: "🤲" },
  { id: "jaco-raquel",       year: -1921, display: "1921 a.C.",          pt: "Jacó se Casa com Raquel",            en: "Jacob Marries Rachel",                ref: "Gênesis 29:28",   emoji: "🐑" },
  { id: "jaco-luta",         year: -1906, display: "1906 a.C.",          pt: "Jacó Luta com o Anjo",               en: "Jacob Wrestles with God",             ref: "Gênesis 32",      emoji: "🤼" },
  { id: "jose-potifar",      year: -1889, display: "1889 a.C.",          pt: "José Acusado pela Mulher de Potifar",en: "Potiphar's Wife Accuses Joseph",      ref: "Gênesis 39:7",    emoji: "🚪" },
  { id: "jose-revela",       year: -1875, display: "1875 a.C.",          pt: "José se Revela aos Irmãos",          en: "Joseph Reveals His Identity",         ref: "Gênesis 45",      emoji: "🤗" },
  { id: "moises-midia",      year: -1486, display: "1486 a.C.",          pt: "Moisés Foge para Midiã",             en: "Moses Flees into Midian",             ref: "Êxodo 2:11",      emoji: "🏜️" },
  { id: "sarca",             year: -1446, display: "1446 a.C.",          pt: "Moisés e a Sarça Ardente",           en: "Moses and the Burning Bush",          ref: "Êxodo 3",         emoji: "🌿" },
  { id: "pascoa",            year: -1446, display: "1446 a.C.",          pt: "A Primeira Páscoa",                  en: "The First Passover",                  ref: "Êxodo 12",        emoji: "🕯️" },
  { id: "tabernaculo",       year: -1445, display: "1445 a.C.",          pt: "O Tabernáculo é Erguido",            en: "The Tabernacle Is Erected",           ref: "Êxodo 40",        emoji: "🏕️" },
  { id: "espias",            year: -1445, display: "1445 a.C.",          pt: "Os Doze Espias em Canaã",            en: "The Twelve Spies",                    ref: "Números 13",      emoji: "🍇" },
  { id: "agua-rocha",        year: -1407, display: "1407 a.C.",          pt: "Água da Rocha em Meribá",            en: "Water from the Rock at Meribah",      ref: "Números 20",      emoji: "💧" },
  { id: "balaao",            year: -1407, display: "1407 a.C.",          pt: "Balaão e a Jumenta",                 en: "Balaam and the Angel",                ref: "Números 22",      emoji: "🐴" },
  { id: "raabe",             year: -1406, display: "1406 a.C.",          pt: "Raabe Esconde os Espias",            en: "Rahab Welcomes the Spies",            ref: "Josué 2",         emoji: "🪢" },
  { id: "jordao",            year: -1406, display: "1406 a.C.",          pt: "A Travessia do Rio Jordão",          en: "The Israelites Cross the Jordan",     ref: "Josué 3",         emoji: "🏞️" },
  { id: "samuel-nasc",       year: -1100, display: "1100 a.C.",          pt: "Nascimento de Samuel",               en: "Birth of Samuel",                     ref: "1 Samuel 1",      emoji: "🙏" },
  { id: "arca-capturada",    year: -1070, display: "1070 a.C.",          pt: "Os Filisteus Capturam a Arca",       en: "Philistines Take the Ark",            ref: "1 Samuel 4",      emoji: "📦" },
  { id: "davi-ungido",       year: -1024, display: "1024 a.C.",          pt: "Samuel Unge Davi em Belém",          en: "Samuel Anoints David",                ref: "1 Samuel 16",     emoji: "🫒" },
  { id: "davi-poupa-saul",   year: -1011, display: "1011 a.C.",          pt: "Davi Poupa a Vida de Saul",          en: "David Spares Saul's Life",            ref: "1 Samuel 24",     emoji: "🗡️" },
  { id: "morte-saul",        year: -1010, display: "1010 a.C.",          pt: "A Morte de Saul e Jônatas",          en: "Saul and His Sons Killed",            ref: "1 Samuel 31",     emoji: "🛡️" },
  { id: "davi-bateseba",     year: -993,  display: "993 a.C.",           pt: "Davi e Bate-Seba",                   en: "David and Bathsheba",                 ref: "2 Samuel 11",     emoji: "🌙" },
  { id: "absalao",           year: -972,  display: "972 a.C.",           pt: "A Morte de Absalão",                 en: "Absalom Slain by Joab",               ref: "2 Samuel 18",     emoji: "🌳" },
  { id: "julgamento-salomao",year: -967,  display: "967 a.C.",           pt: "O Julgamento de Salomão",            en: "Solomon Asks for Wisdom",             ref: "1 Reis 3",        emoji: "⚖️" },
  { id: "elias-corvos",      year: -863,  display: "863 a.C.",           pt: "Elias Alimentado pelos Corvos",      en: "Elijah Fed by Ravens",                ref: "1 Reis 17:3",     emoji: "🐦" },
  { id: "naama",             year: -849,  display: "849 a.C.",           pt: "A Cura de Naamã",                    en: "The Healing of Naaman",               ref: "2 Reis 5",        emoji: "💦" },
  { id: "isaias-visao",      year: -739,  display: "739 a.C.",           pt: "A Visão de Isaías no Templo",        en: "Isaiah's Vision and Commission",      ref: "Isaías 6",        emoji: "🪽" },
  { id: "senaqueribe",       year: -701,  display: "701 a.C.",           pt: "Senaqueribe Ameaça Jerusalém",       en: "Sennacherib Threatens Jerusalem",     ref: "2 Reis 19",       emoji: "🏰" },
  { id: "jeremias",          year: -627,  display: "627 a.C.",           pt: "O Chamado de Jeremias",              en: "The Call of Jeremiah",                ref: "Jeremias 1",      emoji: "🌱" },
  { id: "josias-livro",      year: -621,  display: "621 a.C.",           pt: "O Livro da Lei é Encontrado",        en: "Hilkiah Finds the Book of the Law",   ref: "2 Reis 22:8",     emoji: "📚" },
  { id: "daniel-recusa",     year: -605,  display: "605 a.C.",           pt: "Daniel Recusa a Comida do Rei",      en: "Daniel Refuses the King's Portion",   ref: "Daniel 1",        emoji: "🥬" },
  { id: "sonho-nabuco",      year: -604,  display: "604 a.C.",           pt: "A Estátua do Sonho de Nabucodonosor",en: "Daniel Interprets the Dream",         ref: "Daniel 2",        emoji: "🗿" },
  { id: "ossos-secos",       year: -585,  display: "585 a.C.",           pt: "O Vale de Ossos Secos",              en: "The Valley of Dry Bones",             ref: "Ezequiel 37",     emoji: "🦴" },
  { id: "escrita-parede",    year: -539,  display: "539 a.C.",           pt: "A Escrita na Parede",                en: "The Handwriting on the Wall",         ref: "Daniel 5",        emoji: "🖐️" },
  { id: "ester-salva",       year: -473,  display: "473 a.C.",           pt: "Ester Salva Seu Povo",               en: "Esther's Banquet Saves Her People",   ref: "Ester 7",         emoji: "🍽️" },
  { id: "muralha",           year: -444,  display: "444 a.C.",           pt: "A Reconstrução da Muralha",          en: "Completion of the Wall",              ref: "Neemias 6:15",    emoji: "🧱" },
  { id: "malaquias",         year: -430,  display: "430 a.C.",           pt: "A Profecia de Malaquias",            en: "The Word of the LORD by Malachi",     ref: "Malaquias 1–4",   emoji: "📜" },

  // ===== EXPANSÃO — Novo Testamento =====
  { id: "joao-batista-nasc", year: -6,    display: "6 a.C.",             pt: "Nascimento de João Batista",         en: "Birth of John the Baptist",           ref: "Lucas 1",         emoji: "👶" },
  { id: "magos",             year: -5,    display: "5 a.C.",             pt: "A Visita dos Magos",                 en: "The Visit of the Magi",               ref: "Mateus 2",        emoji: "🎁" },
  { id: "fuga-egito",        year: -5,    display: "5 a.C.",             pt: "A Fuga para o Egito",                en: "The Escape to Egypt",                 ref: "Mateus 2:13",     emoji: "🌙" },
  { id: "tentacao",          year: 27,    display: "27 d.C.",            pt: "A Tentação no Deserto",              en: "The Temptation of Jesus",             ref: "Mateus 4",        emoji: "🏜️" },
  { id: "discipulos",        year: 27,    display: "27 d.C.",            pt: "Jesus Chama os Primeiros Discípulos",en: "Jesus Calls His First Disciples",     ref: "Mateus 4:18",     emoji: "🎣" },
  { id: "samaritana",        year: 27,    display: "27 d.C.",            pt: "Jesus e a Mulher Samaritana",        en: "The Woman at the Well",               ref: "João 4",          emoji: "🪣" },
  { id: "paralitico",        year: 28,    display: "28 d.C.",            pt: "A Cura do Paralítico",               en: "Jesus Heals a Paralytic",             ref: "Mateus 9",        emoji: "🛏️" },
  { id: "tempestade",        year: 28,    display: "28 d.C.",            pt: "Jesus Acalma a Tempestade",          en: "Jesus Calms the Storm",               ref: "Marcos 4:35",     emoji: "⛈️" },
  { id: "joao-decapitado",   year: 29,    display: "29 d.C.",            pt: "João Batista é Decapitado",          en: "John the Baptist Beheaded",           ref: "Mateus 14",       emoji: "⚔️" },
  { id: "anda-aguas",        year: 29,    display: "29 d.C.",            pt: "Jesus Anda sobre as Águas",          en: "Jesus Walks on Water",                ref: "Mateus 14:22",    emoji: "🌊" },
  { id: "adultera",          year: 29,    display: "29 d.C.",            pt: "Jesus e a Mulher Adúltera",          en: "The Woman Caught in Adultery",        ref: "João 8",          emoji: "🪨" },
  { id: "dez-leprosos",      year: 30,    display: "30 d.C.",            pt: "Jesus Cura os Dez Leprosos",         en: "Jesus Cleanses the Ten Lepers",       ref: "Lucas 17",        emoji: "🙌" },
  { id: "entrada-triunfal",  year: 30,    display: "30 d.C.",            pt: "A Entrada Triunfal em Jerusalém",    en: "The Triumphal Entry",                 ref: "Mateus 21",       emoji: "🌴" },
  { id: "ultima-ceia",       year: 30,    display: "30 d.C.",            pt: "A Última Ceia",                      en: "The Last Supper",                     ref: "Mateus 26",       emoji: "🥖" },
  { id: "ascensao",          year: 30,    display: "30 d.C.",            pt: "A Ascensão de Jesus",                en: "The Ascension",                       ref: "Atos 1",          emoji: "☁️" },
  { id: "filipe-etiope",     year: 31,    display: "31 d.C.",            pt: "Filipe e o Etíope",                  en: "Philip and the Ethiopian",            ref: "Atos 8:26",       emoji: "🛞" },
  { id: "filipos",           year: 49,    display: "49 d.C.",            pt: "Paulo e Silas na Prisão de Filipos", en: "Paul and Silas in Philippi",          ref: "Atos 16",         emoji: "🎵" },
  { id: "atenas",            year: 49,    display: "49 d.C.",            pt: "Paulo no Areópago de Atenas",        en: "Paul in Athens",                      ref: "Atos 17",         emoji: "🏛️" },
  { id: "paulo-preso",       year: 59,    display: "59 d.C.",            pt: "Paulo Preso em Jerusalém",           en: "Paul Arrested in Jerusalem",          ref: "Atos 21",         emoji: "⛓️" },
  { id: "roma",              year: 62,    display: "62 d.C.",            pt: "Paulo Prega em Roma",                en: "Paul Preaches at Rome",               ref: "Atos 28:11",      emoji: "🏟️" },
];

// mantém a lista em ordem cronológica
CARDS.sort((a, b) => a.year - b.year);
